#!/usr/bin/env bash
# stop.sh - Archive session and generate metrics
# Part of PILOT - Fail-safe design (always exits 0)

PILOT_HOME="${HOME}/.kiro/pilot"
HOT_MEMORY="${PILOT_HOME}/memory/hot"
WARM_MEMORY="${PILOT_HOME}/memory/warm"
COLD_MEMORY="${PILOT_HOME}/memory/cold"
METRICS_DIR="${PILOT_HOME}/metrics"
CACHE_DIR="${PILOT_HOME}/.cache"

# Ensure directories exist
mkdir -p "$HOT_MEMORY" "$WARM_MEMORY" "$COLD_MEMORY" "$METRICS_DIR" 2>/dev/null || true

# Get input JSON from STDIN (Kiro sends hook events via STDIN, not arguments)
input_json=$(cat 2>/dev/null || echo "{}")

# Timestamps
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SESSION_DATE=$(date +"%Y-%m-%d")
SESSION_TIME=$(date +"%H-%M-%S")

# Get session ID (from input or persisted file)
get_session_id() {
    local json="$1"
    local sid=""
    if command -v jq >/dev/null 2>&1; then
        sid=$(echo "$json" | jq -r '.sessionId // .session_id // empty' 2>/dev/null) || true
    fi
    if [ -z "$sid" ] && [ -f "$CACHE_DIR/current-session-id" ]; then
        sid=$(cat "$CACHE_DIR/current-session-id" 2>/dev/null) || true
    fi
    echo "${sid:-unknown}"
}

SESSION_ID=$(get_session_id "$input_json")

# Archive directory
ARCHIVE_DIR="$COLD_MEMORY/sessions/$SESSION_DATE"
mkdir -p "$ARCHIVE_DIR" 2>/dev/null || true

# Calculate metrics
calc_metrics() {
    local prompts=0 tools=0 success=0 failures=0
    
    [ -f "$HOT_MEMORY/current-session.jsonl" ] && prompts=$(wc -l < "$HOT_MEMORY/current-session.jsonl" 2>/dev/null | tr -d ' ') || true
    
    if [ -f "$HOT_MEMORY/tool-usage.jsonl" ]; then
        tools=$(grep -c "\"session_id\":\"$SESSION_ID\"" "$HOT_MEMORY/tool-usage.jsonl" 2>/dev/null) || true
        success=$(grep "\"session_id\":\"$SESSION_ID\"" "$HOT_MEMORY/tool-usage.jsonl" 2>/dev/null | grep -c '"success":true') || true
        failures=$(grep "\"session_id\":\"$SESSION_ID\"" "$HOT_MEMORY/tool-usage.jsonl" 2>/dev/null | grep -c '"success":false') || true
    fi
    
    echo "{\"prompts\":${prompts:-0},\"tools\":${tools:-0},\"success\":${success:-0},\"failures\":${failures:-0}}"
}

# Analyze algorithm phases
analyze_phases() {
    [ ! -f "$HOT_MEMORY/algorithm-phases.jsonl" ] && echo "No phase data" && return
    
    local o=$(grep -c '"phase":"OBSERVE"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || o=0
    local t=$(grep -c '"phase":"THINK"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || t=0
    local p=$(grep -c '"phase":"PLAN"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || p=0
    local b=$(grep -c '"phase":"BUILD"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || b=0
    local e=$(grep -c '"phase":"EXECUTE"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || e=0
    local v=$(grep -c '"phase":"VERIFY"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || v=0
    local l=$(grep -c '"phase":"LEARN"' "$HOT_MEMORY/algorithm-phases.jsonl" 2>/dev/null) || l=0
    
    echo "O:$o T:$t P:$p B:$b E:$e V:$v L:$l"
}

METRICS=$(calc_metrics)
PHASES=$(analyze_phases)

# Create session summary
cat > "$ARCHIVE_DIR/summary-$SESSION_TIME.md" 2>/dev/null << EOF || true
# Session: $SESSION_DATE $SESSION_TIME

**ID:** $SESSION_ID
**Archived:** $TIMESTAMP

## Metrics
\`\`\`
$METRICS
\`\`\`

## Algorithm Phases
$PHASES

---
*Generated by PILOT*
EOF

# Archive session files
[ -f "$HOT_MEMORY/current-session.jsonl" ] && cp "$HOT_MEMORY/current-session.jsonl" "$ARCHIVE_DIR/session-$SESSION_TIME.jsonl" 2>/dev/null || true
[ -f "$HOT_MEMORY/tool-usage.jsonl" ] && grep "\"session_id\":\"$SESSION_ID\"" "$HOT_MEMORY/tool-usage.jsonl" > "$ARCHIVE_DIR/tools-$SESSION_TIME.jsonl" 2>/dev/null || true
[ -f "$HOT_MEMORY/algorithm-phases.jsonl" ] && grep "\"session_id\":\"$SESSION_ID\"" "$HOT_MEMORY/algorithm-phases.jsonl" > "$ARCHIVE_DIR/phases-$SESSION_TIME.jsonl" 2>/dev/null || true

# Save final session metrics
cat > "$METRICS_DIR/session-$SESSION_ID.json" 2>/dev/null << EOF || true
{"session_id":"$SESSION_ID","ended_at":"$TIMESTAMP","status":"completed","metrics":$METRICS,"phases":"$PHASES"}
EOF

echo "✅ Session archived: $ARCHIVE_DIR/summary-$SESSION_TIME.md"
exit 0
