#!/usr/bin/env bash
# stop.sh - Archive session, synthesize learnings, and generate metrics
# Part of PILOT (Platform for Intelligent Lifecycle Operations and Tools)
#
# FOUNDATION FEATURES:
# - Memory: Archive session to cold storage, update warm memory
# - Intelligence: Extract learnings from session patterns
# - Monitoring: Generate session metrics summary
#
# INPUT: JSON from Kiro (first argument) with session info
# OUTPUT: Confirmation message to stdout

set -euo pipefail

PILOT_HOME="${HOME}/.kiro/pilot"
MEMORY_DIR="${PILOT_HOME}/memory"
HOT_MEMORY="${MEMORY_DIR}/hot"
WARM_MEMORY="${MEMORY_DIR}/warm"
COLD_MEMORY="${MEMORY_DIR}/cold"
METRICS_DIR="${PILOT_HOME}/metrics"

# Ensure directories exist
mkdir -p "${HOT_MEMORY}" "${WARM_MEMORY}" "${COLD_MEMORY}" "${METRICS_DIR}"

# Get timestamps
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
SESSION_DATE=$(date +"%Y-%m-%d")
SESSION_TIME=$(date +"%H-%M-%S")

# Parse input JSON (Kiro provides this as first argument)
input_json="${1:-{}}"

# Extract session ID
SESSION_ID=$(echo "${input_json}" | grep -o '"sessionId"[[:space:]]*:[[:space:]]*"[^"]*"' 2>/dev/null | sed 's/"sessionId"[[:space:]]*:[[:space:]]*"//;s/"$//' || echo "unknown")

# Archive directory for this session
ARCHIVE_DIR="${COLD_MEMORY}/sessions/${SESSION_DATE}"
mkdir -p "${ARCHIVE_DIR}"

# ============================================================================
# MONITORING: Calculate session metrics
# ============================================================================
calculate_metrics() {
    local prompt_count=0
    local tool_count=0
    local tool_success=0
    local tool_failures=0
    local security_blocks=0
    
    # Count prompts
    if [ -f "${HOT_MEMORY}/current-session.jsonl" ]; then
        prompt_count=$(wc -l < "${HOT_MEMORY}/current-session.jsonl" 2>/dev/null | tr -d ' ' || echo 0)
    fi
    
    # Count tool usage
    if [ -f "${HOT_MEMORY}/tool-usage.jsonl" ]; then
        tool_count=$(grep -c "\"session_id\":\"${SESSION_ID}\"" "${HOT_MEMORY}/tool-usage.jsonl" 2>/dev/null || echo 0)
        tool_success=$(grep "\"session_id\":\"${SESSION_ID}\"" "${HOT_MEMORY}/tool-usage.jsonl" 2>/dev/null | grep -c '"success":true' || echo 0)
        tool_failures=$(grep "\"session_id\":\"${SESSION_ID}\"" "${HOT_MEMORY}/tool-usage.jsonl" 2>/dev/null | grep -c '"success":false' || echo 0)
    fi
    
    # Count security blocks
    if [ -f "${HOT_MEMORY}/security.log" ]; then
        security_blocks=$(grep -c "BLOCKED" "${HOT_MEMORY}/security.log" 2>/dev/null || echo 0)
    fi
    
    echo "{\"prompts\":${prompt_count},\"tools\":${tool_count},\"success\":${tool_success},\"failures\":${tool_failures},\"security_blocks\":${security_blocks}}"
}

METRICS=$(calculate_metrics)

# ============================================================================
# INTELLIGENCE: Analyze algorithm phase usage
# ============================================================================
analyze_phases() {
    if [ ! -f "${HOT_MEMORY}/algorithm-phases.jsonl" ]; then
        echo "No phase data"
        return
    fi
    
    local observe=$(grep -c '"phase":"OBSERVE"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    local think=$(grep -c '"phase":"THINK"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    local plan=$(grep -c '"phase":"PLAN"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    local build=$(grep -c '"phase":"BUILD"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    local execute=$(grep -c '"phase":"EXECUTE"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    local verify=$(grep -c '"phase":"VERIFY"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    local learn=$(grep -c '"phase":"LEARN"' "${HOT_MEMORY}/algorithm-phases.jsonl" 2>/dev/null || echo 0)
    
    echo "O:${observe} T:${think} P:${plan} B:${build} E:${execute} V:${verify} L:${learn}"
}

PHASE_ANALYSIS=$(analyze_phases)

# ============================================================================
# MEMORY: Create session summary
# ============================================================================
SUMMARY_FILE="${ARCHIVE_DIR}/summary-${SESSION_TIME}.md"
{
    echo "# Session: ${SESSION_DATE} ${SESSION_TIME}"
    echo ""
    echo "**ID:** ${SESSION_ID}"
    echo "**Archived:** ${TIMESTAMP}"
    echo ""
    echo "## Metrics"
    echo "\`\`\`"
    echo "${METRICS}"
    echo "\`\`\`"
    echo ""
    echo "## Algorithm Phases"
    echo "${PHASE_ANALYSIS}"
    echo ""
    echo "---"
    echo "*Generated by PILOT*"
} > "${SUMMARY_FILE}"

# ============================================================================
# MEMORY: Archive session files
# ============================================================================

# Archive current session log
if [ -f "${HOT_MEMORY}/current-session.jsonl" ] && [ -s "${HOT_MEMORY}/current-session.jsonl" ]; then
    cp "${HOT_MEMORY}/current-session.jsonl" "${ARCHIVE_DIR}/session-${SESSION_TIME}.jsonl"
    > "${HOT_MEMORY}/current-session.jsonl"
fi

# Archive tool usage (session entries only)
if [ -f "${HOT_MEMORY}/tool-usage.jsonl" ]; then
    grep "\"session_id\":\"${SESSION_ID}\"" "${HOT_MEMORY}/tool-usage.jsonl" > "${ARCHIVE_DIR}/tools-${SESSION_TIME}.jsonl" 2>/dev/null || true
fi

# Archive security log
if [ -f "${HOT_MEMORY}/security.log" ] && [ -s "${HOT_MEMORY}/security.log" ]; then
    cp "${HOT_MEMORY}/security.log" "${ARCHIVE_DIR}/security-${SESSION_TIME}.log"
fi

# Archive algorithm phases
if [ -f "${HOT_MEMORY}/algorithm-phases.jsonl" ]; then
    grep "\"session_id\":\"${SESSION_ID}\"" "${HOT_MEMORY}/algorithm-phases.jsonl" > "${ARCHIVE_DIR}/phases-${SESSION_TIME}.jsonl" 2>/dev/null || true
fi

# ============================================================================
# INTELLIGENCE: Extract learnings from failures
# ============================================================================
if [ -f "${HOT_MEMORY}/failures.jsonl" ] && [ -s "${HOT_MEMORY}/failures.jsonl" ]; then
    LEARNINGS_FILE="${WARM_MEMORY}/learnings-${SESSION_DATE}.md"
    {
        echo ""
        echo "## Session ${SESSION_TIME}"
        echo ""
        echo "Failures to review:"
        tail -5 "${HOT_MEMORY}/failures.jsonl" | while read -r line; do
            tool=$(echo "${line}" | grep -o '"tool":"[^"]*"' | sed 's/"tool":"//;s/"$//')
            echo "- ${tool}"
        done
    } >> "${LEARNINGS_FILE}"
fi

# ============================================================================
# MONITORING: Save final session metrics
# ============================================================================
cat > "${METRICS_DIR}/session-${SESSION_ID}.json" << EOF
{
  "session_id": "${SESSION_ID}",
  "ended_at": "${TIMESTAMP}",
  "status": "completed",
  "metrics": ${METRICS},
  "phases": "${PHASE_ANALYSIS}"
}
EOF

# ============================================================================
# MEMORY: Update warm memory index
# ============================================================================
{
    echo "# PILOT Memory Index"
    echo ""
    echo "**Updated:** ${TIMESTAMP}"
    echo ""
    echo "## Recent Sessions"
    find "${COLD_MEMORY}/sessions" -name "summary-*.md" -type f 2>/dev/null | sort -r | head -10 | while read -r file; do
        echo "- $(basename "$(dirname "${file}")")/$(basename "${file}" .md)"
    done
    echo ""
    echo "## Stats"
    echo "- Hot: $(find "${HOT_MEMORY}" -type f 2>/dev/null | wc -l | tr -d ' ') files"
    echo "- Warm: $(find "${WARM_MEMORY}" -type f 2>/dev/null | wc -l | tr -d ' ') files"
    echo "- Cold: $(find "${COLD_MEMORY}" -type f 2>/dev/null | wc -l | tr -d ' ') files"
} > "${WARM_MEMORY}/index.md"

# ============================================================================
# Cleanup: Compress old archives (older than 30 days)
# ============================================================================
find "${COLD_MEMORY}/sessions" -name "*.jsonl" -mtime +30 -exec gzip {} \; 2>/dev/null || true
find "${COLD_MEMORY}/sessions" -name "*.log" -mtime +30 -exec gzip {} \; 2>/dev/null || true

# Output confirmation
echo "✅ Session archived: ${ARCHIVE_DIR}/summary-${SESSION_TIME}.md"

exit 0
